server:
  port: 8085
  servlet:
    context-path: /booking

spring:
  application:
    name: booking-service
  datasource:
    url: "jdbc:mysql://localhost:3306/booking_service"
    #    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    event: http://localhost:8084/event
