server:
  port: 8082
  servlet:
    context-path: /customer

spring:
  application:
    name: customer-service
  datasource:
    url: "jdbc:mysql://localhost:3306/customer_service"
    #    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:

