server:
  port: 8084
  servlet:
    context-path: /event

spring:
  application:
    name: event-service
  datasource:
    url: "jdbc:mysql://localhost:3306/event_service"
    #    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:

